"""new_id_column

Revision ID: 409804a0733a
Revises: '50dbc746c2dd'
Create Date: 2025-09-01 13:24:02.757207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409804a0733a'
down_revision: Union[str, None] = '50dbc746c2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('open_library_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_open_library_id'), 'books', ['open_library_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_open_library_id'), table_name='books')
    op.drop_column('books', 'open_library_id')
    # ### end Alembic commands ###