"""Completar modelo book

Revision ID: 63ad535a1e11
Revises: 'c7853a317703'
Create Date: 2025-09-04 02:38:20.404824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ad535a1e11'
down_revision: Union[str, None] = 'c7853a317703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('want_to_read_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('read_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('currently_reading_count', sa.Integer(), nullable=True))
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('books', 'currently_reading_count')
    op.drop_column('books', 'read_count')
    op.drop_column('books', 'want_to_read_count')
    op.drop_column('books', 'rating_count')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###