"""Book con posibilidad de varios autores

Revision ID: 9600420d4984
Revises: '409804a0733a'
Create Date: 2025-09-03 02:23:25.231858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9600420d4984'
down_revision: Union[str, None] = '409804a0733a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_languages')
    op.add_column('books', sa.Column('work_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('books_author_id_fkey'), 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('books_author_id_fkey'), 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'work_id')
    op.create_table('book_languages',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('book_languages_book_id_fkey')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('book_languages_language_id_fkey')),
    sa.PrimaryKeyConstraint('book_id', 'language_id', name=op.f('book_languages_pkey'))
    )
    # ### end Alembic commands ###