"""Eliminar tabla language

Revision ID: c7853a317703
Revises: 'cc0584ea83a1'
Create Date: 2025-09-03 03:34:54.491049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7853a317703"
down_revision: Union[str, None] = "cc0584ea83a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_languages_id"), table_name="languages")
    op.drop_index(op.f("ix_languages_name"), table_name="languages")
    op.drop_constraint("books_language_id_fkey", "books", type_="foreignkey")
    op.drop_table("languages")
    op.add_column("books", sa.Column("language", sa.String(), nullable=True))
    op.drop_column("books", "language_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column("language_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("books_language_id_fkey"), "books", "languages", ["language_id"], ["id"]
    )
    op.drop_column("books", "language")
    op.create_table(
        "languages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("languages_pkey")),
    )
    op.create_index(op.f("ix_languages_name"), "languages", ["name"], unique=True)
    op.create_index(op.f("ix_languages_id"), "languages", ["id"], unique=False)
    # ### end Alembic commands ###
