# alembic.ini

[alembic]
# Ruta a la carpeta que contiene los scripts de migración.
# Como este archivo y la carpeta 'alembic' están en el mismo nivel,
# la ruta es simplemente 'alembic'.
script_location = alembic

# Plantilla para nombrar los nuevos archivos de migración.
file_template = %%(rev)s_%%(slug)s

# URL de conexión a la base de datos.
# IMPORTANTE: No pondremos la URL aquí directamente.
# La configuraremos para que se lea desde el entorno en el archivo 'env.py'.
sqlalchemy.url = postgresql://user:password@db:5432/openlibrary


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S